### ISSUE TITLE
[user] Add user/group integration

### ISSUE THREAD

**Issue by ndufreche** [backbee/BbCoreJs#245]
- [x] Update user to get the groups list in was is assign
  - [x] update REST controller backbee/BackBee#225 
  - [x] update js templates
- [x] Update group to get the users list in was is assign
  - [x] update REST controller backbee/BackBee#227
  - [x] update js templates
  - [x] create user listing action in popin render
- [x] enable DND action
  - [x] chrome compatibility
  - [x] firefox compatibility
  - [x] create patch action
  - [x] update User REST patch action backbee/BackBee#225
- [x] Translation
  - [x] English
  - [x] French

**Comment by mickaelandrieu** [comment]
would you mind to add a check list of all features you have to do to resolve this and check what you have already done ?

**Comment by ndufreche** [comment]
yes
